spring:
  application:
    name: pdf-converter
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/mydb
    username: postgres
    password: rajnamai
  jpa:
    hibernate:
      ddl-auto: create
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  profiles:
    active: dev
  thymeleaf:
    prefix:  file:src/main/resources/templates/
    suffix: .html
    mode: HTML
    cache: false
  resources:
    static-locations: file:src/main/resources/static/
    cache:
      period: 0
  servlet:
    multipart:
      max-file-size: 40MB
      max-request-size: 40MB
#  devtools:
#    restart:
#      poll-interval: 2s
#      quite-period: 1s
#      additional-paths: classpath:/templates/

